unbind C-b
set -g prefix C-_
bind C-_ send-prefix

# vim like pane fucosing
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# vim mode in copy mode
set-window-option -g mode-keys vi

# true color
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# iceberg (https://github.com/gkeep/iceberg-dark#tmux)
source-file ~/.config/tmux/iceberg_minimal.tmux.conf

# allow pass through of Kitty protocol
set -g allow-passthrough on

# Caffinate
bind C popup -E -w 60 -h 3 -y 3 "echo '☕ [caffeinate] Preventing sleep... Press Ctrl+C to stop.'; caffeinate -i -d"
